-- ============================================================
-- DA SALUD - BASE DE ACCESO CLIENTES
-- Versión inicial
-- IMPORTANTE:
-- Revisar antes de ejecutar sobre un proyecto Supabase existente.
-- ============================================================

begin;

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'da_salud_org_type') then
    create type public.da_salud_org_type as enum (
      'obra_social',
      'mutual',
      'prepaga',
      'sanatorio',
      'gerenciadora',
      'otro'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'da_salud_member_role') then
    create type public.da_salud_member_role as enum (
      'client_admin',
      'manager',
      'auditor',
      'requester',
      'viewer'
    );
  end if;
end $$;

create table if not exists public.da_salud_organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  legal_name text,
  org_type public.da_salud_org_type not null default 'otro',
  rnas text,
  tax_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.da_salud_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  job_title text,
  is_da_admin boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.da_salud_memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.da_salud_organizations(id) on delete cascade,
  user_id uuid not null references public.da_salud_profiles(id) on delete cascade,
  role public.da_salud_member_role not null default 'viewer',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.da_salud_audit_log (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.da_salud_organizations(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.da_salud_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_da_salud_org_updated_at on public.da_salud_organizations;
create trigger trg_da_salud_org_updated_at
before update on public.da_salud_organizations
for each row execute function public.da_salud_touch_updated_at();

drop trigger if exists trg_da_salud_profile_updated_at on public.da_salud_profiles;
create trigger trg_da_salud_profile_updated_at
before update on public.da_salud_profiles
for each row execute function public.da_salud_touch_updated_at();

create or replace function public.da_salud_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.da_salud_profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_da_salud on auth.users;
create trigger on_auth_user_created_da_salud
after insert on auth.users
for each row execute function public.da_salud_handle_new_user();

create or replace function public.da_salud_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.da_salud_profiles p
    where p.id = auth.uid()
      and p.is_da_admin = true
      and p.active = true
  );
$$;

create or replace function public.da_salud_is_org_member(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.da_salud_memberships m
    where m.organization_id = org_id
      and m.user_id = auth.uid()
      and m.active = true
  );
$$;

create or replace function public.da_salud_has_org_role(
  org_id uuid,
  allowed_roles public.da_salud_member_role[]
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.da_salud_memberships m
    where m.organization_id = org_id
      and m.user_id = auth.uid()
      and m.active = true
      and m.role = any(allowed_roles)
  );
$$;

alter table public.da_salud_organizations enable row level security;
alter table public.da_salud_profiles enable row level security;
alter table public.da_salud_memberships enable row level security;
alter table public.da_salud_audit_log enable row level security;

drop policy if exists "organizations_select" on public.da_salud_organizations;
create policy "organizations_select"
on public.da_salud_organizations
for select
to authenticated
using (
  public.da_salud_is_admin()
  or public.da_salud_is_org_member(id)
);

drop policy if exists "organizations_admin_all" on public.da_salud_organizations;
create policy "organizations_admin_all"
on public.da_salud_organizations
for all
to authenticated
using (public.da_salud_is_admin())
with check (public.da_salud_is_admin());

drop policy if exists "profiles_select_self_or_admin" on public.da_salud_profiles;
create policy "profiles_select_self_or_admin"
on public.da_salud_profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.da_salud_is_admin()
);

drop policy if exists "profiles_update_self_or_admin" on public.da_salud_profiles;
create policy "profiles_update_self_or_admin"
on public.da_salud_profiles
for update
to authenticated
using (
  id = auth.uid()
  or public.da_salud_is_admin()
)
with check (
  id = auth.uid()
  or public.da_salud_is_admin()
);

drop policy if exists "memberships_select" on public.da_salud_memberships;
create policy "memberships_select"
on public.da_salud_memberships
for select
to authenticated
using (
  public.da_salud_is_admin()
  or public.da_salud_is_org_member(organization_id)
);

drop policy if exists "memberships_admin_all" on public.da_salud_memberships;
create policy "memberships_admin_all"
on public.da_salud_memberships
for all
to authenticated
using (public.da_salud_is_admin())
with check (public.da_salud_is_admin());

drop policy if exists "audit_log_select" on public.da_salud_audit_log;
create policy "audit_log_select"
on public.da_salud_audit_log
for select
to authenticated
using (
  public.da_salud_is_admin()
  or (
    organization_id is not null
    and public.da_salud_has_org_role(
      organization_id,
      array['client_admin','manager','auditor']::public.da_salud_member_role[]
    )
  )
);

drop policy if exists "audit_log_insert" on public.da_salud_audit_log;
create policy "audit_log_insert"
on public.da_salud_audit_log
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    public.da_salud_is_admin()
    or (
      organization_id is not null
      and public.da_salud_is_org_member(organization_id)
    )
  )
);

grant execute on function public.da_salud_is_admin() to authenticated;
grant execute on function public.da_salud_is_org_member(uuid) to authenticated;
grant execute on function public.da_salud_has_org_role(uuid, public.da_salud_member_role[]) to authenticated;

commit;

-- ============================================================
-- PASOS POSTERIORES
-- 1) Crear los usuarios desde Supabase Auth o desde la futura app.
-- 2) Marcar manualmente el primer administrador DA Salud:
--
-- update public.da_salud_profiles
-- set is_da_admin = true
-- where email = 'TU_EMAIL_REAL';
--
-- 3) Crear la primera organización:
--
-- insert into public.da_salud_organizations (name, org_type)
-- values ('Cliente de prueba', 'obra_social')
-- returning id;
--
-- 4) Asociar un usuario a esa organización:
--
-- insert into public.da_salud_memberships (organization_id, user_id, role)
-- select
--   'UUID_DE_LA_ORGANIZACION'::uuid,
--   id,
--   'client_admin'
-- from public.da_salud_profiles
-- where email = 'EMAIL_DEL_USUARIO';
-- ============================================================
